# Site settings
title: ML ideabook
description: 'A notebook for Coursera Machine Learning course ideas'
url: 'http://hankaviator.github.io/cdata_blog/' 
baseurl: '/cdata_blog/'
#google_analytics: 'UA-54634914-1'

author:
  name: 'Hank Quakevauld'
#  email: josh@joshgerdes.com
#  twitter_username: joshgerdes
#  github_username:  joshgerdes
#  linkedin_username:  joshgerdes

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: redcarpet

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']